[build]
  command = "zola build --base-url https://cosmicecology.netlify.app"
  publish = "public"

[build.environment]
  ZOLA_VERSION = "0.18.0"

[context.production.environment]
  HUGO_VERSION = ""

# Optional: Custom headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optional: Redirects (if needed)
# [[redirects]]
#   from = "/old-path/*"
#   to = "/new-path/:splat"
#   status = 301